### ISSUE TITLE
Make spiders with a given equipment grid

### ISSUE THREAD

**Issue by flameSla** [ILLISIS/Constructron-Continued#161]
Set the default spider equipment grid:
https://github.com/flameSla/equipped-spider
https://github.com/flameSla/equipped-spider/blob/master/control.lua

This will make it easier to create an army of spiders and eliminate mistakes with the wrong set of equipment.

**Comment by gabfv** [comment]
As a workaround, I've placed a constructon with all the equipment I want except for power producing equipment. So the constructon remains at the place I've set it and it still says "Needs Equipment". Since it doesn't accept any jobs, I can just copy/paste with shift+right click/shift+left click to a new constructon with the minimal amount of equipment to add (for most setups that require only one type of power generating equipment, this also means you can just open up the equipment grid and do a quick transfer with ctrl+left click).

**Comment by HEROgold** [comment]
I just saw this issue, and though of https://mods.factorio.com/mod/equipment-gantry, this mod enables you and makes sure your spiders have the wanted equipment before you even collect them

**Comment by ILLISIS** [comment]
Equipment requests is in scope for 2.0
