### ISSUE TITLE
Can't get it to Build if it is in range of a roboport.

### ISSUE THREAD

**Issue by Dme128** [ILLISIS/Constructron-Continued#18]
if I build  a ghost near a roboport it try's to go build it but if the roboport builds it first the Constructron just sits in one spot. i turned debug on it tells me "ACTION: request_items" then "CONDITION: request_done" and it will not stop repeating that even if i delete the Constructron or the Service Station. The Constructron  did turn blue and request the items and has the items but is now just sitting there.   If i build anything else it will not go for it even if i remove the items from the Constructron  it will not reset or try for a new task. I have not changed any default settings except the debug mode i included screenshots of my mods using with it.
[Factorio Mods list Constructron.zip](https://github.com/ILLISIS/Constructron-Continued/files/8007155/Factorio.Mods.list.Constructron.zip)
.

**Comment by ILLISIS** [comment]
Hi

It sounds like there are there unfulfilled items being requested from logistics, can you confirm if that is the case or not?

**Comment by Dme128** [comment]
the request is empty 
Today  I tried building accouple things on the map and it did a few and stopped it is just sitting at the last place it went it still has items in its Inventory but it is done building in that spot.  i only have one built. it is not returning to it's base or to the next build. i don't even see a path planned for it.

**Comment by Dme128** [comment]
I tried and the web page wont take it."i think it is to big"  I uploaded to my drive you should be able to get it it is called new start.
https://drive.google.com/drive/folders/1FWbqvQuOcB1xJ33oTVhnEfKHab-SpOMd?usp=sharing

**Comment by ILLISIS** [comment]
Hi

Thanks for that. 
The reason the Constructions are standing around is because they have over shot their destination because they move to quickly. I will add logic to rerun the go_to_position action again but I still highly recommend removing some exoskeletons from the equipment grids as it will take max_jobtime(default 2 mins) to retry the action. The most you can use in a default grid size is three with one fusion reactor and I run with this in my games fine.

Additionally, v1.0.7 will include many validation checks to prevent a lot of crashes previously received so judging from my experience loading your save, you will benefit from this version significantly.

**Comment by Dme128** [comment]
Ok Thank You. this make I use to experiment with and check out mods I might want to use in my normal world.  I really Like this mod! Again Thank You!
