### ISSUE TITLE
Spidertron Remote

### ISSUE THREAD

**Issue by Ravager000** [ILLISIS/Constructron-Continued#87]
https://lua-api.factorio.com/latest/events.html#on_player_used_spider_remote

A Constructron was trying to path into a lake.I don't know if it would time out eventually. Using a remote to skip or cancel current bad behaviour.

**Comment by Ravager000** [comment]
or to skip a missing construction material. is it suposed to time out at some point ?

**Comment by ILLISIS** [comment]
@Ravager000
Hi

The landfill functionality is still regarded as experimental, this is because it is just a brute force way to try and achieve it due to pathing issues. You can use /ctron reset all to restart the jobs when one gets stuck.

With regards to missing construction materials, you can clear the requests that are not getting fulfilled to send it out but ultimately the mod is for use in the late game where materials should be bountiful. Ctrons will roam to multiple stations if you have multiple networks but that is based on a timer and has no logic to it.
